spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://YOUR_DB_HOST:3306/lecture_feedback # DB 주소 입력
    username: YOUR_DB_USERNAME # DB 유저 이름 입력
    password: YOUR_DB_PASSWORD # DB password 입력
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

file:
  upload-dir: uploads/

openai:
  api:
    key: YOUR_OPENAI_API_KEY  # OpenAI API 키 입력
    url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo

clova:
  secret-key: YOUR_CLOVA_API_KEY  # Clova Speech API 키 입력
  base-url: https://clovaspeech-gw.ncloud.com/external/v1/YOUR_PROJECT_ID/YOUR_CLIENT_ID
